[project]
name = "iot-stream-analytics"
version = "0.1.0"
description = "Real-Time IoT Telemetry & Analytics Pipeline"
authors = [
    { name = "Francesco Russo", email = "russo.checco@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"

[tool.poetry.dependencies]
pyspark = { version = "3.5.4", extras = ["sql"] }
kafka-python = ">=3.0.11"
influxdb-client = ">=1.9.0"

[tool.poetry]
packages = [{ include = "iot_stream_analytics", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
